### PR TITLE
Push notification added for new message received

### PR DESCRIPTION
**Pull request by fayeed**
Uses HTML5 Notification API to display notification.

### CODE REVIEW

**Review by leifriksheim — COMMENTED** [review]
@fayeed Looks good! Could we put notification logic into a Vuex action? We might want to trigger notifications from other places in the app, and also it would be cool if we could save user preferences about notifications so the user can enable/disable notifications etc.

**Comment by fayeed** [comment]
I could put notification logic in Vuex but the problem is each notification will behave differently, for example, this notification will take the user to the channel it belongs to, so we will have to create a lot of actions for each type, maybe move it in a utility function. 

As for enabling notifications, it would be better to have community-wide or channel-specific enable/disable options. If we are doing community-wide then we can have an option inside the dropdown menu for the community, we don't have any type of channel menu so not sure what would be a better approach UX-wise.

**Comment by leifriksheim** [comment]
Yep, I agree that we don't need them in actions as we are not mutating any state as a side effect.

I would suggest:
- Make some utility functions for easier use of the Notifications Web API
- `CommunityState` could have a `preferences.notifications` object that contains user preferences about channel notifications.
- `ChannelState` could have a `notifications` object that contains preferences about the channel notifications. Could also have a `mute` boolean to mute the channel.
- Create a right-click context menu with `j-popover` element on each channel list item.

**Comment by fayeed** [comment]
Added context menu to each channel with an option to mute/unmute notification & moved the `showMessageNotification` to a separate utility function.

**Comment by jdeepee** [comment]
@fayeed are notifications being triggered all the time or are they only being triggered when the application is minimized/out of view of the OS?

**Comment by fayeed** [comment]
@jdeepee They should trigger when the active channel or community is different and that channel is not mute. I am going to add the minimized functionality but first wanted to test it.

**Comment by jdeepee** [comment]
@fayeed this is awesome nice work

**Pull request merged**
