### PR TITLE
System tray

### PR DESCRIPTION
**Pull request by fayeed**
This PR adds the functionality to close the app from the system tray and have it minimized to the tray like how Slack & Discord behave.

### CODE REVIEW

**Comment by jdeepee** [comment]
Nice idea @fayeed ill check out the PR when at home since on WSL it doesnt seem to go into my system tray

**Comment by fayeed** [comment]
Yeah, it won't work on WSL, so had to create a demo project on windows and copy the code later here.

**Comment by jdeepee** [comment]
@fayeed this is looking great but can we also add an option on the system tray icon to open the application again?

**Comment by fayeed** [comment]
If you click the icon again it should open the app again.

**Comment by jdeepee** [comment]
On Linux it only brings up the menu with an option for exit

**Comment by fayeed** [comment]
@jdeepee added the open option.

**Comment by jdeepee** [comment]
Waiting for review from @leifriksheim then we can merge

**Pull request merged**
