### PR TITLE
WIP: Optimization: bump holochain

### PR DESCRIPTION
**Pull request by jdeepee**
Blocked by: https://github.com/holochain/holochain/pull/829

So we can have working mac binaries

### CODE REVIEW

**Comment by harlantwood** [comment]
@jdeepee if are using nix, and you want to use this holochain PR before it is merged,  you can use the hash of the current head of the PR.  Here's my default.nix where I'm doing that:

```
let
  holonixPath = builtins.fetchTarball {
    url = "https://github.com/holochain/holonix/archive/3e94163765975f35f7d8ec509b33c3da52661bd1.tar.gz";
    sha256 = "sha256:07sl281r29ygh54dxys1qpjvlvmnh7iv1ppf79fbki96dj9ip7d2";
  };
  holonix = import (holonixPath) {
    includeHolochainBinaries = true;
    holochainVersionId = "custom";

    holochainVersion = {
     rev = "20d2570c36b9e8da087a565a1ed644562cc92136";  # current head of https://github.com/holochain/holochain/pull/829
     sha256 = "1bfy9q7bg929p7kzz96g4r9lhmb10v2zyywycmr3ifi1jq60rd50";
     cargoSha256 = "sha256:1gv2zhslraxiq8v5644mxb2d1sl0md6i79rsjppcf0gi7n6pd6zi";
     bins = {
       holochain = "holochain";
       hc = "hc";
     };
    };
    holochainOtherDepsNames = ["lair-keystore"];
  };
in holonix.main
```

**Comment by harlantwood** [comment]
... having said that, this PR will probably not get merged as is, so it's definitely bleeding edge.

**Comment by jdeepee** [comment]
hey @harlantwood Ill probably just wait until the fix is made in holochain since it takes some work for us to update holochain here. But thanks for reporting that bug, that saved us a lot of diagnosis time, hope they sort it soon!

**Comment by harlantwood** [comment]
@jdeepee looks like my PR did get merged as is!

**Pull request merged**
